export const UNIT_TYPES = {
  brushSwordsman: {
    key: "brushSwordsman",
    displayName: "Brush Swordsman",
    shortName: "Swordsman",
    role: "melee",
    cost: 25,
    hp: 80,
    damage: 12,
    attackInterval: 800,
    range: 28,
    speed: 70,
    radius: 12,
    color: 0xece6d6,
  },
  quillArcher: {
    key: "quillArcher",
    displayName: "Quill Archer",
    shortName: "Archer",
    role: "range",
    cost: 35,
    hp: 45,
    damage: 9,
    attackInterval: 700,
    range: 180,
    speed: 60,
    radius: 11,
    color: 0xc69c4a,
  },
  foldedSentinel: {
    key: "foldedSentinel",
    displayName: "Folded Sentinel",
    shortName: "Sentinel",
    role: "tank",
    cost: 60,
    hp: 260,
    damage: 14,
    attackInterval: 1100,
    range: 32,
    speed: 38,
    radius: 16,
    color: 0x9c8c6a,
  },
  inkMortar: {
    key: "inkMortar",
    displayName: "Ink Mortar",
    shortName: "Mortar",
    role: "splash",
    cost: 80,
    hp: 55,
    damage: 18,
    attackInterval: 1600,
    range: 210,
    splashRadius: 55,
    speed: 38,
    radius: 13,
    color: 0x4a3a26,
  },
  paperDragon: {
    key: "paperDragon",
    displayName: "Paper Dragon",
    shortName: "Dragon",
    role: "juggernaut",
    cost: 200,
    hp: 650,
    damage: 38,
    attackInterval: 1300,
    range: 42,
    speed: 44,
    radius: 22,
    color: 0xe6c87a,
  },
};

export const UNIT_LIST = [
  UNIT_TYPES.brushSwordsman,
  UNIT_TYPES.quillArcher,
  UNIT_TYPES.foldedSentinel,
  UNIT_TYPES.inkMortar,
  UNIT_TYPES.paperDragon,
];
